FROM ruby:2.3.7

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

RUN mkdir /alpha-blog
WORKDIR /alpha-blog

COPY Gemfile /alpha-blog/Gemfile
COPY Gemfile.lock /alpha-blog/Gemfile.lock

RUN bundle install

COPY . /alpha-blog