version: "2"

volumes:
  db_prod: {}
services:
  db_prod:
    image: postgres
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      RAILS_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db_prod